services:
  # Ingestion Service: Scrapes/Loads data into DuckDB
  ingestion:
    build:
      context: .
      dockerfile: ingestion/Dockerfile
    volumes:
      - ./pokemon_tcg_pipeline.duckdb:/app/pokemon_tcg_pipeline.duckdb

  # Transformation Service: Runs dbt models
  transformations:
    build:
      context: .
      dockerfile: transformations/Dockerfile
    volumes:
      - ./pokemon_tcg_pipeline.duckdb:/app/pokemon_tcg_pipeline.duckdb
      - ./transformations:/app/transformations
    working_dir: /app/transformations
    command: run --profiles-dir .
    depends_on:
      ingestion:
        condition: service_completed_successfully
