version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio1
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    volumes:
      - ${HOME}/minio/data:/data
    user: "$(id -u):$(id -g)"
    command: server /data --console-address ":9090"
