name: 'pokemon_tcg_transform'
version: '1.0.0'
config-version: 2

profile: 'pokemon_tcg_transform'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by 'dbt clean'
  - "target"
  - "dbt_packages"

models:
  pokemon_tcg_transform:
    # Config for all models
    staging:
      +materialized: view
      +schema: staging
    semantic:
      +materialized: table
      +schema: semantic
    consumption:
      +materialized: table
      +schema: consumption
